#%RAML 1.0 NamedExample
{ 
   "address":[ 
      { 
         "addressId":2,
         "contactId":1,
         "addressType":"Home",
         "number":1234,
         "street":"blah blah St",
         "unit":"1 a",
         "city":"Somewhere",
         "state":"WV",
         "zipcode":"12345"
      }
   ]
}